apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubedash-gateway
  namespace: devx
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
      honorLabels: true
      bearerTokenSecret:
        key: token
        name: observability-grafana-agent-operator-token
  namespaceSelector:
    matchNames:
      - devx
  selector:
    matchLabels:
      app: stage-kubedash-gateway
