apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: stage-kubedash-gateway
    argo-cd-platform.trendyol.com/argo: s-devx-p1-1mars-devx-stage-kubedash-gateway 
  name: stage-kubedash-gateway-deneme
  namespace: devx
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    path: /metrics
    port: http
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - devx
  selector:
    matchLabels:
      app: stage-kubedash-gateway
      #argo-cd-platform.trendyol.com/argo: s-devx-p1-1mars-devx-stage-kubedash-gateway
