# permissions for end users to view hpawatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hpaToKeda
    app.kubernetes.io/managed-by: kustomize
  name: hpawatcher-viewer-role
rules:
- apiGroups:
  - autoscaling.mydomain.com
  resources:
  - hpawatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.mydomain.com
  resources:
  - hpawatchers/status
  verbs:
  - get
